require_relative "./PGA_Tour_Reader/version"
require_relative "./PGA_Tour_Reader/cli.rb"
require_relative "./PGA_tournament.rb"
require_relative "./PGA_season.rb"
require_relative "./PGA_Tour_scraper.rb"
require_relative "./PGA_Tour_parser.rb"
require_relative "./PGA_Tour_Reader/cli_helper.rb"
require 'date'
require 'open-uri'
require 'nokogiri'
